// ========== 法律页面 i18n ==========
(function () {
    'use strict';
    const { I18n } = window.MyLuck;

    // ===== 共享 =====
    I18n.add('zh', { 'legal.back': '← 返回首页' });
    I18n.add('en', { 'legal.back': '← Back to Home' });

    // ===== 隐私政策 =====
    I18n.add('en', {
        'privacy.h1': '🔒 Privacy Policy',
        'privacy.friendly': '<strong>In short:</strong> We take your privacy seriously. MyLuck is a purely static website — all tests run in your browser, and we don\'t secretly collect personal information. Here are the details, but if you\'re short on time, just know: "We don\'t collect your data" 😊',
        'privacy.h2_1': 'What Do We Collect?',
        'privacy.p1': 'Short answer: <strong>Almost nothing</strong>.',
        'privacy.li1': 'We don\'t require you to register or log in',
        'privacy.li2': 'We don\'t collect your name, email, phone, or other personal information',
        'privacy.li3': 'All tests (luck, MBTI, color, etc.) run entirely in your browser — results are never sent to any server',
        'privacy.li4': 'Your language preference is stored in your browser\'s localStorage — only on your own device',
        'privacy.h2_2': 'Third-Party Services',
        'privacy.p2': 'To keep the site running and improve your experience, we use some third-party services with their own privacy policies:',
        'privacy.li5': '<strong>Hosting</strong> — Our site is hosted on a cloud platform, which may log visitor IP addresses for security purposes.',
        'privacy.li6': '<strong>Anonymous Analytics</strong> — We use privacy-friendly analytics to understand which pages are popular, helping us improve. These tools do not collect personally identifiable information or use cookies for tracking.',
        'privacy.li7': '<strong>Advertising</strong> — If ads are present, ad providers may use cookies to serve relevant ads. You can manage cookies through your browser settings.',
        'privacy.h2_3': 'Cookies',
        'privacy.p3': 'MyLuck itself does not use cookies. However, third-party services (such as ads) may. Your browser settings can help you manage these.',
        'privacy.h2_4': 'Suitable for All Ages',
        'privacy.p4': 'Our content is suitable for all age groups and contains nothing inappropriate for minors. We do not actively collect any information from minors.',
        'privacy.h2_5': 'Questions?',
        'privacy.p5': 'If you have any privacy questions or concerns, feel free to reach out through our Wish Wall, and we\'ll respond as soon as possible.',
        'privacy.update': 'Last updated: February 2026',
    });

    // ===== 使用条款 =====
    I18n.add('en', {
        'terms.h1': '📜 Terms of Use',
        'terms.friendly': '<strong>Plain version:</strong> MyLuck is a purely entertainment website. We offer fun little quizzes you can use for free and share with friends. We only have two small requests: be kind to other users, and don\'t take the test results too seriously~',
        'terms.h2_1': 'What Is This Site?',
        'terms.p1': 'MyLuck (myluck.top) is a fun interactive entertainment website offering daily luck tests, MBTI personality tests, color personality tests, and more. All test results are randomly generated by computer algorithms, <strong>for entertainment purposes only</strong>.',
        'terms.h2_2': 'About Test Results',
        'terms.li1': 'All results are randomly generated by algorithms — they have no scientific basis or predictive power',
        'terms.li2': 'Do not use results as the basis for any important decisions',
        'terms.li3': 'We do not provide any form of fortune-telling, divination, or supernatural services',
        'terms.li4': 'If you find the tests fun, share with friends! If not, that\'s totally fine too ✌️',
        'terms.h2_3': 'Community Guidelines',
        'terms.p2': 'If you use the comment/discussion features, please:',
        'terms.li5': 'Be friendly and respectful — everyone deserves kindness',
        'terms.li6': 'No advertising, spam, or unfriendly content',
        'terms.li7': 'No content that violates applicable laws and regulations',
        'terms.li8': 'Do not use the site for any form of fraud',
        'terms.h2_4': 'Intellectual Property',
        'terms.p3': 'The site\'s design and original content belong to MyLuck. Quoted sayings belong to their authors. You\'re welcome to share test results on social media — we\'re glad you enjoy them!',
        'terms.h2_5': 'Advertising',
        'terms.p4': 'The site may contain third-party ads. We are not responsible for the accuracy of ad content — please use your own judgment when clicking ads.',
        'terms.h2_6': 'Applicable Law',
        'terms.p5': 'These terms are governed by the laws applicable in your jurisdiction. For users in mainland China, the laws of the People\'s Republic of China apply. For international users, local laws of your region apply.',
        'terms.update': 'Last updated: February 2026',
    });

    // ===== 免责声明 =====
    I18n.add('en', {
        'disc.h1': '🎪 Disclaimer',
        'disc.friendly': '<strong>One-liner:</strong> MyLuck is a purely entertainment website. All "luck tests" and "personality tests" are randomly generated by computers — think of them like fortune cookies: fun but not to be taken seriously!',
        'disc.h2_1': '🎯 What We Do',
        'disc.p1': 'We make fun interactive quizzes! Including daily luck tests, MBTI personality tests, lucky color tests, fun personality tags, and more. The purpose is simple — to brighten your day and add a sprinkle of fun to the routine 🌶️',
        'disc.h2_2': '⚡ Key Points',
        'disc.li1': 'All test results are <strong>randomly generated by algorithms</strong> — no fortune-telling, divination, or superstition is involved',
        'disc.li2': 'Results have <strong>no scientific basis, predictive power, or practical guidance</strong>',
        'disc.li3': 'Please approach all results with an <strong>entertainment mindset</strong> — just have fun!',
        'disc.li4': 'Do not make important decisions based on test results (e.g., investments, relationships, career choices)',
        'disc.h2_3': '🤝 Our Commitments',
        'disc.li5': 'We comply with applicable laws and regulations in all operating regions',
        'disc.li6': 'We do not collect your personal information',
        'disc.li7': 'We do not contain any illegal, harmful, or inappropriate content',
        'disc.li8': 'If you find any issues, please let us know through the Wish Wall and we\'ll address them promptly',
        'disc.h2_4': '📋 Legal Compliance',
        'disc.p2': 'This site complies with applicable laws and regulations, including but not limited to:',
        'disc.li9': 'Data protection regulations (GDPR, CCPA, PIPL, and other applicable frameworks)',
        'disc.li10': 'Consumer protection laws',
        'disc.li11': 'Advertising regulations',
        'disc.li12': 'Privacy and data security laws',
        'disc.h2_5': '💡 Finally',
        'disc.p3': 'Life is serious enough — quizzes are just for fun. We hope MyLuck brings a little bit of happiness and good vibes to your every day 🍀',
        'disc.update': 'Last updated: February 2026',
    });

    // 应用翻译
    I18n.apply();

    // ===== 国际法律适配通知 =====
    // 如果用户是非中国地区，显示国际法律适配提示
    function addInternationalNotice() {
        const lang = I18n.lang;
        if (lang !== 'en') return; // 只有英文用户才显示

        const legalCard = document.querySelector('.legal-card');
        if (!legalCard) return;

        // 检查是否已添加
        if (legalCard.querySelector('.intl-notice')) return;

        const notice = document.createElement('div');
        notice.className = 'friendly-note intl-notice';
        notice.style.marginTop = '20px';
        notice.style.borderLeftColor = '#74b9ff';
        notice.innerHTML = `
            <strong>🌍 International Users:</strong> MyLuck serves users worldwide. 
            We comply with applicable privacy and data protection regulations in your jurisdiction, 
            including GDPR (EU), CCPA (California, USA), PIPEDA (Canada), and the Australian Privacy Act. 
            If you have region-specific concerns, please contact us.
        `;
        legalCard.appendChild(notice);
    }

    // 延迟执行（等 i18n apply 完成）
    setTimeout(addInternationalNotice, 100);
    document.addEventListener('langchange', () => {
        const existing = document.querySelector('.intl-notice');
        if (existing) existing.remove();
        setTimeout(addInternationalNotice, 50);
    });
})();
