// ========== 天赋专属事件库 (Talent-Specific Events) ==========
// 每种特殊天赋 100+ 独立戏剧化事件
// 通过 window.TALENT_EVENTS 供 liferestart.js 合并使用
(function () {
    'use strict';

    const TALENT_EVENTS = [

    // ============================================================
    //  1. 异世界转生 (isekai) — 100+ 事件
    // ============================================================
    // --- 觉醒与穿越 ---
    { text: { zh: '⚡ 你在18岁生日那天被神秘光芒笼罩，穿越到了异世界！', en: '⚡ On your 18th birthday, a mysterious light transported you to another world!' }, cond: { minAge: 18, maxAge: 18, hasTag: 'isekai' }, effects: { spr: 5, tag: 'in_isekai' } },
    { text: { zh: '你醒来发现自己躺在一片草原上，空气中弥漫着魔力的气息。', en: 'You woke up on a vast grassland, the air thick with magical energy.' }, cond: { minAge: 18, maxAge: 19, hasTag: 'in_isekai', chance: 0.5 }, effects: { spr: 1 } },
    { text: { zh: '一位老者告诉你，这个世界正处于魔王威胁之下。', en: 'An elder told you this world is under the Demon King\'s threat.' }, cond: { minAge: 18, maxAge: 19, hasTag: 'in_isekai', chance: 0.4 }, effects: { tag: 'isekai_quest' } },
    { text: { zh: '你发现自己能看到"状态面板"，上面显示着你的数值。', en: 'You can see a "Status Panel" displaying your stats.' }, cond: { minAge: 18, maxAge: 19, hasTag: 'in_isekai', chance: 0.3 }, effects: { int: 1, tag: 'isekai_status' } },
    { text: { zh: '你遇到了一只会说话的猫，它自称是你的向导。', en: 'You met a talking cat claiming to be your guide.' }, cond: { minAge: 18, maxAge: 20, hasTag: 'in_isekai', chance: 0.3 }, effects: { spr: 1, tag: 'isekai_guide' } },

    // --- 冒险初期 ---
    { text: { zh: '🗡️ 你在异世界觉醒了强大的力量，被封为勇者！', en: '🗡️ You awakened great power in the other world, hailed as a Hero!' }, cond: { minAge: 19, maxAge: 22, hasTag: 'in_isekai', minStr: 5, chance: 0.5 }, effects: { str: 3, chr: 3, tag: 'isekai_hero' } },
    { text: { zh: '你加入了冒险者公会，接了第一个任务——清除哥布林。', en: 'You joined the Adventurer\'s Guild and took your first quest — goblins.' }, cond: { minAge: 18, maxAge: 20, hasTag: 'in_isekai', chance: 0.4 }, effects: { str: 1, tag: 'isekai_adventurer' } },
    { text: { zh: '你在副本里差点死掉，幸好队友及时救了你。', en: 'You almost died in a dungeon, but your teammate saved you just in time.' }, cond: { minAge: 19, maxAge: 25, hasTag: 'isekai_adventurer', chance: 0.3 }, effects: { str: -1, spr: 1 } },
    { text: { zh: '你打败了你的第一个Boss——一只巨型蜘蛛！', en: 'You defeated your first boss — a giant spider!' }, cond: { minAge: 19, maxAge: 22, hasTag: 'isekai_adventurer', minStr: 4, chance: 0.4 }, effects: { str: 2, spr: 1, mny: 1, tag: 'isekai_boss1' } },
    { text: { zh: '你学会了火球术！虽然第一次差点烧到自己。', en: 'You learned Fireball! Almost burned yourself the first time.' }, cond: { minAge: 18, maxAge: 23, hasTag: 'in_isekai', minInt: 5, chance: 0.4 }, effects: { int: 1, tag: 'isekai_magic' } },
    { text: { zh: '你和队友一起在篝火旁分享各自的故事，异世界的夜空格外美丽。', en: 'You shared stories by the campfire — the other world\'s sky is breathtaking.' }, cond: { minAge: 19, maxAge: 30, hasTag: 'in_isekai', chance: 0.3 }, effects: { spr: 2 } },
    { text: { zh: '你在异世界第一次尝到了"魔法烤肉"，比前世任何食物都好吃！', en: 'You tasted "Magic BBQ" for the first time — better than anything from your past life!' }, cond: { minAge: 18, maxAge: 25, hasTag: 'in_isekai', chance: 0.3 }, effects: { spr: 1 } },
    { text: { zh: '你意外闯入了精灵族的领地，被箭指着鼻子质问。', en: 'You accidentally wandered into Elven territory and were interrogated at arrowpoint.' }, cond: { minAge: 19, maxAge: 25, hasTag: 'in_isekai', chance: 0.25 }, effects: { spr: -1 } },
    { text: { zh: '你帮助精灵族解决了水源污染问题，获得了他们的友谊。', en: 'You helped the Elves solve a water pollution crisis, earning their friendship.' }, cond: { minAge: 19, maxAge: 28, hasTag: 'in_isekai', minInt: 5, chance: 0.2 }, effects: { chr: 2, tag: 'isekai_elf_friend' } },
    { text: { zh: '精灵公主送了你一把附魔弓，说"这是我们的谢礼"。', en: 'The Elven princess gave you an enchanted bow as thanks.' }, cond: { minAge: 19, maxAge: 30, hasTag: 'isekai_elf_friend', chance: 0.3 }, effects: { str: 2 } },

    // --- 成长与挑战 ---
    { text: { zh: '你发现自己拥有"鉴定"技能，能看透一切物品的属性。', en: 'You discovered your "Appraise" skill — you can see any item\'s stats.' }, cond: { minAge: 19, maxAge: 24, hasTag: 'in_isekai', minInt: 6, chance: 0.3 }, effects: { int: 2, mny: 1 } },
    { text: { zh: '你偶然发现了一个远古遗迹，里面藏着失落的魔法书。', en: 'You discovered an ancient ruin containing a lost spellbook.' }, cond: { minAge: 20, maxAge: 30, hasTag: 'in_isekai', minInt: 5, chance: 0.2 }, effects: { int: 3, tag: 'isekai_ancient' } },
    { text: { zh: '你在异世界的黑市买到了一件神器，但价格贵得离谱。', en: 'You bought a divine artifact on the black market — absurdly expensive.' }, cond: { minAge: 20, maxAge: 35, hasTag: 'in_isekai', minMny: 5, chance: 0.15 }, effects: { str: 3, mny: -3 } },
    { text: { zh: '你被卷入了王国的政变！险些丧命。', en: 'You got caught in a kingdom coup! Nearly lost your life.' }, cond: { minAge: 20, maxAge: 30, hasTag: 'in_isekai', chance: 0.15 }, effects: { str: -1, spr: -2, tag: 'isekai_coup' } },
    { text: { zh: '你帮助正统王子夺回王位，被授予爵位。', en: 'You helped the rightful prince reclaim the throne and were knighted.' }, cond: { minAge: 21, maxAge: 35, hasTag: 'isekai_coup', minStr: 5, chance: 0.4 }, effects: { chr: 3, mny: 3, tag: 'isekai_knight' } },
    { text: { zh: '你通过前世的知识制造了肥皂，在异世界发了大财！', en: 'Using past-life knowledge, you invented soap and made a fortune!' }, cond: { minAge: 19, maxAge: 30, hasTag: 'in_isekai', minInt: 5, chance: 0.25 }, effects: { mny: 4, int: 1, tag: 'isekai_inventor' } },
    { text: { zh: '📖 你利用前世的知识在异世界发明了许多东西。', en: '📖 Using your past life knowledge, you invented many things.' }, cond: { minAge: 19, maxAge: 40, hasTag: 'in_isekai', minInt: 6, chance: 0.3 }, effects: { int: 2, mny: 3 } },
    { text: { zh: '你教会了异世界的人做"拉面"，开了第一家拉面店。', en: 'You taught people in the other world how to make ramen — opened the first shop!' }, cond: { minAge: 20, maxAge: 35, hasTag: 'in_isekai', chance: 0.2 }, effects: { mny: 3, spr: 2, chr: 1 } },
    { text: { zh: '你用现代数学知识解决了异世界魔法阵的难题。', en: 'You solved a magical circle puzzle using modern mathematics.' }, cond: { minAge: 19, maxAge: 35, hasTag: 'in_isekai', minInt: 7, chance: 0.2 }, effects: { int: 2, chr: 1 } },
    { text: { zh: '你在异世界的竞技场一路过关斩将，获得了"斗神"称号。', en: 'You fought your way through the arena and earned the title "Battle God".' }, cond: { minAge: 20, maxAge: 30, hasTag: 'in_isekai', minStr: 7, chance: 0.15 }, effects: { str: 3, chr: 2, tag: 'isekai_champion' } },
    { text: { zh: '你在森林深处遇到了一条受伤的龙，决定救治它。', en: 'You found an injured dragon deep in the forest and decided to heal it.' }, cond: { minAge: 20, maxAge: 35, hasTag: 'in_isekai', chance: 0.15 }, effects: { spr: 2, tag: 'isekai_dragon' } },
    { text: { zh: '那条龙痊愈后成了你的坐骑！你骑着龙翱翔天际！', en: 'The dragon recovered and became your mount! You soar through the skies!' }, cond: { minAge: 21, maxAge: 40, hasTag: 'isekai_dragon', chance: 0.4 }, effects: { str: 2, chr: 3, spr: 3, tag: 'isekai_dragonrider' } },

    // --- 领地与建设 ---
    { text: { zh: '🏰 你在异世界建立了自己的领地，成为一方领主。', en: '🏰 You built your own territory, becoming a Lord.' }, cond: { minAge: 22, maxAge: 35, hasTag: 'in_isekai', chance: 0.3 }, effects: { mny: 5, chr: 2, tag: 'isekai_lord' } },
    { text: { zh: '你的领地吸引了大量移民，人口翻了三倍。', en: 'Your territory attracted many immigrants — population tripled.' }, cond: { minAge: 23, maxAge: 40, hasTag: 'isekai_lord', chance: 0.3 }, effects: { mny: 2, chr: 1 } },
    { text: { zh: '你在领地建立了学校，教人们现代知识。', en: 'You built a school in your territory, teaching modern knowledge.' }, cond: { minAge: 23, maxAge: 40, hasTag: 'isekai_lord', minInt: 6, chance: 0.3 }, effects: { int: 1, chr: 2, spr: 1 } },
    { text: { zh: '邻国对你的领地发动了侵略战争！', en: 'A neighboring kingdom declared war on your territory!' }, cond: { minAge: 24, maxAge: 40, hasTag: 'isekai_lord', chance: 0.2 }, effects: { spr: -2, tag: 'isekai_war' } },
    { text: { zh: '你带领军队击退了入侵者，领民高呼你的名字！', en: 'You led your army to repel the invaders — your people chant your name!' }, cond: { minAge: 24, maxAge: 45, hasTag: 'isekai_war', minStr: 5, chance: 0.5 }, effects: { str: 2, chr: 3, spr: 3 } },
    { text: { zh: '你引入了异世界版的"工业革命"，领地经济飞速发展。', en: 'You introduced an industrial revolution — your territory\'s economy boomed.' }, cond: { minAge: 25, maxAge: 45, hasTag: 'isekai_lord', hasTag2: 'isekai_inventor', chance: 0.3 }, effects: { mny: 5, int: 1 } },
    { text: { zh: '你的领地举办了第一届"异世界运动会"，盛况空前。', en: 'Your territory hosted the first "Isekai Olympics" — a grand success.' }, cond: { minAge: 25, maxAge: 45, hasTag: 'isekai_lord', chance: 0.2 }, effects: { chr: 2, spr: 2 } },

    // --- 感情线 ---
    { text: { zh: '💕 你在异世界遇到了命中注定的人。', en: '💕 You met your destiny in the other world.' }, cond: { minAge: 20, maxAge: 35, hasTag: 'in_isekai', minChr: 5, chance: 0.3 }, effects: { spr: 4, tag: 'partner' } },
    { text: { zh: '你和异世界的恋人在月光下起舞，如同童话。', en: 'You danced with your lover under moonlight, like a fairy tale.' }, cond: { minAge: 21, maxAge: 40, hasTag: 'in_isekai', hasTag2: 'partner', chance: 0.25 }, effects: { spr: 2 } },
    { text: { zh: '异世界的女祭司对你表白了，她说"从你穿越来的那一刻，我就在等你"。', en: 'The priestess confessed: "I\'ve been waiting since the moment you arrived."' }, cond: { minAge: 20, maxAge: 30, hasTag: 'in_isekai', minChr: 6, chance: 0.15 }, effects: { spr: 3, chr: 1 } },
    { text: { zh: '你的异世界后宫越来越大，每天都有修罗场。', en: 'Your isekai harem keeps growing — drama every single day.' }, cond: { minAge: 20, maxAge: 35, hasTag: 'in_isekai', minChr: 8, chance: 0.1 }, effects: { chr: 2, spr: -1 } },
    { text: { zh: '魔族公主偷偷帮助你，因为她厌倦了战争。', en: 'The Demon Princess secretly helped you — she\'s tired of war.' }, cond: { minAge: 22, maxAge: 35, hasTag: 'in_isekai', chance: 0.15 }, effects: { spr: 2, int: 1, tag: 'isekai_demon_princess' } },
    { text: { zh: '你收了一个兽人族的少年为徒弟，他叫你"师傅"。', en: 'You took a beastfolk boy as your apprentice — he calls you "Master".' }, cond: { minAge: 22, maxAge: 40, hasTag: 'in_isekai', chance: 0.2 }, effects: { spr: 1, chr: 1, tag: 'isekai_disciple' } },
    { text: { zh: '你的弟子成长得很快，已经能独当一面了。', en: 'Your apprentice grew rapidly and can now hold his own.' }, cond: { minAge: 25, maxAge: 50, hasTag: 'isekai_disciple', chance: 0.4 }, effects: { spr: 2, chr: 1 } },

    // --- 魔王线 ---
    { text: { zh: '你发现魔王其实是被操控的，真正的幕后黑手是堕落的神。', en: 'You discovered the Demon King is being controlled — the true villain is a fallen god.' }, cond: { minAge: 25, maxAge: 40, hasTag: 'in_isekai', minInt: 7, chance: 0.15 }, effects: { int: 2, tag: 'isekai_truth' } },
    { text: { zh: '你和魔王联手对抗堕落之神！', en: 'You allied with the Demon King against the fallen god!' }, cond: { minAge: 26, maxAge: 45, hasTag: 'isekai_truth', chance: 0.4 }, effects: { str: 2, spr: 2, tag: 'isekai_alliance' } },
    { text: { zh: '👑 你击败了魔王，拯救了异世界！名扬万世！', en: '👑 You defeated the Demon King and saved the world! Legendary!' }, cond: { minAge: 25, maxAge: 40, hasTag: 'in_isekai', minStr: 7, minInt: 6, chance: 0.2 }, effects: { chr: 5, spr: 5, str: 3, tag: 'isekai_savior' } },
    { text: { zh: '你和堕落之神进行了最终决战，你的伙伴们都在你身后！', en: 'The final battle against the fallen god — all your companions stand behind you!' }, cond: { minAge: 28, maxAge: 50, hasTag: 'isekai_alliance', minStr: 7, chance: 0.3 }, effects: { str: 3, spr: 3, chr: 2, tag: 'isekai_final' } },
    { text: { zh: '你赢了！异世界恢复了和平，所有种族齐聚庆祝。', en: 'You won! Peace is restored. All races gather to celebrate.' }, cond: { minAge: 28, maxAge: 55, hasTag: 'isekai_final', chance: 0.6 }, effects: { spr: 5, chr: 3 } },
    { text: { zh: '你被封为"异界圣王"，建立了多种族共存的联合王国。', en: 'You were crowned "Holy King of the Other World" — a multi-race united kingdom.' }, cond: { minAge: 30, maxAge: 55, hasTag: 'isekai_savior', chance: 0.3 }, effects: { chr: 3, mny: 5, tag: 'isekai_king' } },

    // --- 日常/搞笑 ---
    { text: { zh: '你在异世界发明了"异世界版抽水马桶"，被称为文明的功臣。', en: 'You invented the flush toilet in the other world — hailed as a civilization hero.' }, cond: { minAge: 19, maxAge: 35, hasTag: 'in_isekai', minInt: 4, chance: 0.15 }, effects: { chr: 1, spr: 2 } },
    { text: { zh: '你试图教异世界的人"剪刀石头布"，他们觉得这是高深的魔法。', en: 'You taught "Rock Paper Scissors" — they thought it was advanced magic.' }, cond: { minAge: 18, maxAge: 30, hasTag: 'in_isekai', chance: 0.2 }, effects: { spr: 2 } },
    { text: { zh: '你在异世界开了一家"地球美食"餐馆，排队的人从城门排到王宫。', en: 'You opened an "Earth Cuisine" restaurant — the queue stretched to the palace gates.' }, cond: { minAge: 20, maxAge: 35, hasTag: 'in_isekai', chance: 0.15 }, effects: { mny: 3, spr: 2, chr: 1 } },
    { text: { zh: '异世界没有智能手机，你开始严重戒断反应。', en: 'No smartphones in the other world — severe withdrawal symptoms.' }, cond: { minAge: 18, maxAge: 20, hasTag: 'in_isekai', chance: 0.3 }, effects: { spr: -2 } },
    { text: { zh: '你在异世界的澡堂发生了经典的"偶遇"事件。', en: 'Classic "accidental encounter" at the other world\'s bathhouse.' }, cond: { minAge: 18, maxAge: 30, hasTag: 'in_isekai', chance: 0.15 }, effects: { chr: 1, spr: 1 } },
    { text: { zh: '你被一群史莱姆追着跑了三条街。', en: 'A swarm of slimes chased you through three streets.' }, cond: { minAge: 18, maxAge: 25, hasTag: 'in_isekai', chance: 0.2 }, effects: { str: 1, spr: -1 } },
    { text: { zh: '你和矮人族一起喝酒，喝到了天亮。异世界的酒真带劲。', en: 'You drank with the dwarves until dawn. Their ale packs a punch.' }, cond: { minAge: 20, maxAge: 40, hasTag: 'in_isekai', chance: 0.2 }, effects: { spr: 2, str: -1 } },
    { text: { zh: '你在异世界的图书馆发现了一本"勇者大全"，发现你不是第一个穿越者。', en: 'In the library, you found a "Hero Encyclopedia" — you\'re not the first traveler.' }, cond: { minAge: 19, maxAge: 30, hasTag: 'in_isekai', minInt: 5, chance: 0.15 }, effects: { int: 1, spr: -1 } },
    { text: { zh: '你在异世界收到了系统提示："恭喜，你已存活365天，解锁成就。"', en: 'System alert: "Congratulations! You survived 365 days. Achievement unlocked."' }, cond: { minAge: 19, maxAge: 20, hasTag: 'in_isekai', chance: 0.4 }, effects: { spr: 1 } },

    // --- 危机/挫折 ---
    { text: { zh: '你被异世界的诅咒击中，连续三天变成了一只青蛙。', en: 'Hit by a curse — you turned into a frog for three days.' }, cond: { minAge: 19, maxAge: 35, hasTag: 'in_isekai', chance: 0.1 }, effects: { chr: -2, spr: -1 } },
    { text: { zh: '你在迷宫深处迷路了整整一周，靠蘑菇活了下来。', en: 'Lost in a labyrinth for a week, surviving on mushrooms.' }, cond: { minAge: 19, maxAge: 30, hasTag: 'in_isekai', chance: 0.12 }, effects: { str: -2, int: 1 } },
    { text: { zh: '你的装备在战斗中被打碎了，只能赤手空拳战斗。', en: 'Your equipment shattered in battle — forced to fight barehanded.' }, cond: { minAge: 20, maxAge: 35, hasTag: 'in_isekai', chance: 0.15 }, effects: { str: 1, mny: -2 } },
    { text: { zh: '你遭到了暗杀者的袭击，幸好你的龙坐骑及时出现。', en: 'An assassin attacked you, but your dragon mount arrived just in time.' }, cond: { minAge: 22, maxAge: 40, hasTag: 'isekai_dragonrider', chance: 0.15 }, effects: { spr: -1, str: 1 } },
    { text: { zh: '你被异世界的贵族陷害入狱，在监牢里待了三个月。', en: 'Framed by a noble — you spent three months in prison.' }, cond: { minAge: 20, maxAge: 35, hasTag: 'in_isekai', chance: 0.1 }, effects: { spr: -3, chr: -1, tag: 'isekai_prison' } },
    { text: { zh: '你越狱成功！成为了异世界最大的"悬赏犯"。', en: 'You escaped prison! Now the most wanted person in the other world.' }, cond: { minAge: 20, maxAge: 40, hasTag: 'isekai_prison', chance: 0.5 }, effects: { str: 2, chr: 1, spr: 1 } },
    { text: { zh: '洗清冤屈后你被授予了勋章作为补偿。', en: 'After clearing your name, you received a medal as compensation.' }, cond: { minAge: 21, maxAge: 45, hasTag: 'isekai_prison', minInt: 5, chance: 0.4 }, effects: { chr: 2, mny: 2, spr: 2 } },
    { text: { zh: '你中了毒，必须在三天内找到解药。', en: 'You were poisoned — must find the antidote within three days.' }, cond: { minAge: 19, maxAge: 40, hasTag: 'in_isekai', chance: 0.1 }, effects: { str: -2 } },
    { text: { zh: '你在悬崖边差点摔下去，被神秘力量救了。', en: 'You nearly fell off a cliff but were saved by a mysterious force.' }, cond: { minAge: 19, maxAge: 40, hasTag: 'in_isekai', chance: 0.1 }, effects: { spr: -1 } },
    { text: { zh: '一场瘟疫席卷了异世界，你用前世的医学知识拯救了无数人。', en: 'A plague swept the world — you saved countless lives with modern medicine.' }, cond: { minAge: 22, maxAge: 40, hasTag: 'in_isekai', minInt: 7, chance: 0.1 }, effects: { int: 2, chr: 3, spr: 2 } },

    // --- 探索与发现 ---
    { text: { zh: '你发现了异世界的"传送门"网络，可以瞬间移动到各个大陆。', en: 'You discovered the world\'s teleportation gate network.' }, cond: { minAge: 22, maxAge: 40, hasTag: 'in_isekai', minInt: 6, chance: 0.15 }, effects: { int: 1, spr: 2 } },
    { text: { zh: '你到达了世界的尽头——那里是一片虚空，能看到其他世界。', en: 'You reached the world\'s edge — void, where other worlds are visible.' }, cond: { minAge: 25, maxAge: 50, hasTag: 'in_isekai', chance: 0.08 }, effects: { int: 3, spr: 2 } },
    { text: { zh: '你在海底发现了古代文明的遗迹。', en: 'You discovered ruins of an ancient civilization on the ocean floor.' }, cond: { minAge: 22, maxAge: 40, hasTag: 'in_isekai', chance: 0.1 }, effects: { int: 2, mny: 2 } },
    { text: { zh: '你驯服了一只凤凰！它的羽毛散发着金色的光。', en: 'You tamed a phoenix! Its feathers glow golden.' }, cond: { minAge: 25, maxAge: 45, hasTag: 'in_isekai', minChr: 6, chance: 0.08 }, effects: { chr: 3, str: 1, tag: 'isekai_phoenix' } },
    { text: { zh: '你在空中翱翔时俯视大地，感叹异世界的壮丽。', en: 'Soaring through the sky, you marvel at the other world\'s beauty.' }, cond: { minAge: 22, maxAge: 50, hasTag: 'isekai_dragonrider', chance: 0.3 }, effects: { spr: 2 } },
    { text: { zh: '你进入了"封印之地"，那里沉睡着远古神兽。', en: 'You entered the Sealed Lands, where ancient divine beasts sleep.' }, cond: { minAge: 25, maxAge: 45, hasTag: 'in_isekai', minStr: 6, chance: 0.1 }, effects: { str: 2, int: 1, tag: 'isekai_sealed' } },
    { text: { zh: '远古神兽苏醒了！你和它进行了一场史诗级的战斗。', en: 'The ancient beast awakened! An epic battle ensued.' }, cond: { minAge: 26, maxAge: 50, hasTag: 'isekai_sealed', minStr: 7, chance: 0.4 }, effects: { str: 3, spr: -1 } },
    { text: { zh: '你发现了时间暂停魔法，但每次只能维持10秒。', en: 'You discovered time-stop magic, but it only lasts 10 seconds.' }, cond: { minAge: 22, maxAge: 40, hasTag: 'isekai_magic', minInt: 8, chance: 0.1 }, effects: { int: 2 } },
    { text: { zh: '你在异世界建立了第一所魔法大学！', en: 'You established the first Magic University in the other world!' }, cond: { minAge: 30, maxAge: 50, hasTag: 'isekai_lord', minInt: 8, chance: 0.15 }, effects: { int: 3, chr: 2, spr: 2 } },

    // --- 回忆/思乡 ---
    { text: { zh: '你看着异世界的月亮，想起了前世的家人和朋友。', en: 'Gazing at the other world\'s moon, you thought of your family from before.' }, cond: { minAge: 20, maxAge: 60, hasTag: 'in_isekai', chance: 0.15 }, effects: { spr: -2 } },
    { text: { zh: '你在异世界办了一场"地球文化节"，教大家唱前世的歌。', en: 'You hosted an "Earth Culture Festival" and taught everyone songs from your past life.' }, cond: { minAge: 22, maxAge: 45, hasTag: 'in_isekai', chance: 0.1 }, effects: { spr: 2, chr: 1 } },
    { text: { zh: '你找到了回到原来世界的方法……但你选择留下来。', en: 'You found a way back to your original world... but chose to stay.' }, cond: { minAge: 30, maxAge: 60, hasTag: 'in_isekai', chance: 0.08 }, effects: { spr: 3, tag: 'isekai_stay' } },
    { text: { zh: '你在异世界写了一本自传《来自异世界的勇者》，成为畅销书。', en: 'You wrote an autobiography "Hero from Another World" — it became a bestseller.' }, cond: { minAge: 30, maxAge: 60, hasTag: 'in_isekai', minInt: 6, chance: 0.1 }, effects: { mny: 2, chr: 2, spr: 1 } },
    { text: { zh: '你在梦中短暂回到了原来的世界，醒来时枕头湿了一片。', en: 'In a dream, you briefly returned to your world. You woke to a damp pillow.' }, cond: { minAge: 25, maxAge: 70, hasTag: 'in_isekai', chance: 0.08 }, effects: { spr: -2 } },

    // --- 晚年/传说 ---
    { text: { zh: '你在异世界已经生活了几十年，你的名字成了传说。', en: 'After decades in the other world, your name became legend.' }, cond: { minAge: 50, maxAge: 80, hasTag: 'in_isekai', chance: 0.3 }, effects: { chr: 3, spr: 2 } },
    { text: { zh: '你的弟子们遍布大陆，你被尊称为"大贤者"。', en: 'Your disciples span the continent — you\'re called "The Great Sage".' }, cond: { minAge: 50, maxAge: 80, hasTag: 'isekai_disciple', chance: 0.3 }, effects: { chr: 2, int: 2, spr: 2 } },
    { text: { zh: '你在异世界安详地度过了晚年，被所有人铭记。', en: 'You spent your final years peacefully, remembered by everyone.' }, cond: { minAge: 60, maxAge: 90, hasTag: 'in_isekai', chance: 0.3 }, effects: { spr: 3 } },
    { text: { zh: '异世界为你建造了一座雕像，刻着"来自另一个世界的英雄"。', en: 'The other world built a statue of you: "The Hero from Another World."' }, cond: { minAge: 50, maxAge: 90, hasTag: 'isekai_savior', chance: 0.3 }, effects: { chr: 3, spr: 3 } },
    { text: { zh: '你的故事被异世界的吟游诗人传唱，三百年后仍有人记得。', en: 'Bards sing your tale — still remembered 300 years later.' }, cond: { minAge: 60, maxAge: 95, hasTag: 'in_isekai', chance: 0.2 }, effects: { chr: 2, spr: 3 } },

    // --- 更多魔法/战斗/奇遇 ---
    { text: { zh: '你学会了"空间收纳"魔法，行李再也不是问题。', en: 'You learned "Spatial Storage" magic — luggage is never a problem.' }, cond: { minAge: 19, maxAge: 30, hasTag: 'isekai_magic', chance: 0.2 }, effects: { int: 1 } },
    { text: { zh: '你参加了魔法师考试，获得了S级魔法师资格。', en: 'You passed the Mage Exam and earned S-rank Mage certification.' }, cond: { minAge: 22, maxAge: 35, hasTag: 'isekai_magic', minInt: 8, chance: 0.15 }, effects: { int: 3, chr: 2, tag: 'isekai_srank' } },
    { text: { zh: '你在魔法实验中不小心把自己的头发变成了粉色。', en: 'A magic experiment accident turned your hair pink.' }, cond: { minAge: 19, maxAge: 35, hasTag: 'isekai_magic', chance: 0.15 }, effects: { chr: 1, spr: 1 } },
    { text: { zh: '你研制出了"魔法手机"，彻底改变了异世界的通讯方式。', en: 'You invented the "Magic Phone" — revolutionizing communication.' }, cond: { minAge: 25, maxAge: 45, hasTag: 'isekai_inventor', minInt: 8, chance: 0.1 }, effects: { mny: 4, int: 2, chr: 2 } },
    { text: { zh: '你在异世界的温泉镇度过了一个悠闲的假期。', en: 'You enjoyed a relaxing vacation at the hot springs town.' }, cond: { minAge: 20, maxAge: 60, hasTag: 'in_isekai', chance: 0.15 }, effects: { spr: 3, str: 1 } },
    { text: { zh: '你和同伴一起击败了深海巨兽，获得了稀有材料！', en: 'You and your companions defeated a deep-sea monster — rare materials acquired!' }, cond: { minAge: 22, maxAge: 40, hasTag: 'in_isekai', minStr: 5, chance: 0.12 }, effects: { str: 1, mny: 3 } },
    { text: { zh: '你在异世界的赌场赢了一大笔金币！', en: 'You won big at the other world\'s casino!' }, cond: { minAge: 20, maxAge: 50, hasTag: 'in_isekai', chance: 0.08 }, effects: { mny: 3, spr: 2 } },
    { text: { zh: '你在异世界的赌场输光了所有积蓄……', en: 'You lost all your savings at the casino...' }, cond: { minAge: 20, maxAge: 50, hasTag: 'in_isekai', chance: 0.08 }, effects: { mny: -3, spr: -2 } },
    { text: { zh: '你成了异世界第一个骑着飞空艇环游世界的人。', en: 'You became the first to circumnavigate the world on an airship.' }, cond: { minAge: 25, maxAge: 50, hasTag: 'in_isekai', chance: 0.08 }, effects: { spr: 3, chr: 2 } },
    { text: { zh: '你在异世界开设了第一家"图书馆"，收集了一万本魔法书。', en: 'You opened the first "Library" — collecting 10,000 spellbooks.' }, cond: { minAge: 25, maxAge: 55, hasTag: 'in_isekai', minInt: 7, chance: 0.1 }, effects: { int: 2, chr: 1, spr: 1 } },
    { text: { zh: '异世界的神灵现身，对你说"你的存在本身就是奇迹"。', en: 'A deity appeared and said, "Your very existence is a miracle."' }, cond: { minAge: 30, maxAge: 70, hasTag: 'in_isekai', chance: 0.05 }, effects: { spr: 4, int: 2 } },
    { text: { zh: '你的冒险伙伴为保护你牺牲了，你发誓不会忘记他。', en: 'Your companion sacrificed themselves to protect you. You vowed never to forget.' }, cond: { minAge: 22, maxAge: 45, hasTag: 'in_isekai', chance: 0.08 }, effects: { spr: -4, str: 2, tag: 'isekai_loss' } },
    { text: { zh: '多年后你在他的墓前放上了鲜花，轻声说："我们做到了。"', en: 'Years later, you placed flowers at their grave: "We did it."' }, cond: { minAge: 30, maxAge: 60, hasTag: 'isekai_loss', chance: 0.5 }, effects: { spr: 2 } },
    { text: { zh: '你解锁了"圣光"终极魔法，全大陆只有三个人掌握过。', en: 'You unlocked "Holy Light" ultimate magic — only 3 have ever wielded it.' }, cond: { minAge: 30, maxAge: 60, hasTag: 'isekai_srank', minInt: 9, chance: 0.15 }, effects: { int: 3, chr: 3 } },
    { text: { zh: '你在异世界的集市上遇到了一个来自同一个时代的穿越者！你们聊了一整夜。', en: 'At the marketplace, you met another traveler from your era! You talked all night.' }, cond: { minAge: 20, maxAge: 50, hasTag: 'in_isekai', chance: 0.05 }, effects: { spr: 4 } },
    { text: { zh: '你在异世界组建了一支乐队，用吉他征服了所有人。', en: 'You formed a band in the other world — conquered everyone with guitar.' }, cond: { minAge: 20, maxAge: 40, hasTag: 'in_isekai', chance: 0.08 }, effects: { chr: 2, spr: 2, mny: 1 } },
    { text: { zh: '你发现异世界的某种草药可以治愈地球上的不治之症。', en: 'You found a herb in the other world that can cure incurable diseases on Earth.' }, cond: { minAge: 25, maxAge: 50, hasTag: 'in_isekai', minInt: 7, chance: 0.05 }, effects: { int: 3, spr: 2 } },
    { text: { zh: '你在异世界的魔法锦标赛中获得了冠军！', en: 'You won the championship at the Magic Tournament!' }, cond: { minAge: 22, maxAge: 40, hasTag: 'isekai_magic', minInt: 7, chance: 0.12 }, effects: { int: 2, chr: 3, spr: 2, mny: 2 } },

    // ============================================================
    //  2. 女装大佬 (crossdress) — 100+ 事件
    // ============================================================
    // --- 觉醒 ---
    { text: { zh: '👗 你在15岁时第一次尝试了女装，发现意外地好看。', en: '👗 At 15, you tried crossdressing — surprisingly stunning.' }, cond: { minAge: 15, maxAge: 15, hasTag: 'crossdress' }, effects: { chr: 4, spr: 2, tag: 'cd_awakened' } },
    { text: { zh: '你偷偷穿了姐姐的裙子，在镜子前转了好几圈。', en: 'You secretly wore your sister\'s dress and twirled in front of the mirror.' }, cond: { minAge: 15, maxAge: 16, hasTag: 'cd_awakened', chance: 0.5 }, effects: { spr: 1 } },
    { text: { zh: '你发现自己的睫毛比大多数女生都长，嫉妒死了同班女生。', en: 'Your eyelashes are longer than most girls\' — they\'re jealous.' }, cond: { minAge: 15, maxAge: 17, hasTag: 'cd_awakened', chance: 0.4 }, effects: { chr: 1, spr: 1 } },
    { text: { zh: '你第一次化了妆，同桌没认出来你。', en: 'You put on makeup for the first time — your deskmate didn\'t recognize you.' }, cond: { minAge: 15, maxAge: 17, hasTag: 'cd_awakened', chance: 0.4 }, effects: { chr: 2, spr: 2 } },
    { text: { zh: '你开始研究护肤品，皮肤变得比女生还好。', en: 'You started studying skincare — your skin became better than most girls\'.' }, cond: { minAge: 15, maxAge: 20, hasTag: 'cd_awakened', chance: 0.35 }, effects: { chr: 1, tag: 'cd_skincare' } },

    // --- 校园篇 ---
    { text: { zh: '😳 班上的男同学跟你表白了，你……', en: '😳 A male classmate confessed to you...' }, cond: { minAge: 16, maxAge: 18, hasTag: 'cd_awakened', minChr: 8, chance: 0.2 }, effects: { spr: 1 } },
    { text: { zh: '文化祭上你女装出场，全场尖叫！老师还以为来了新同学。', en: 'At the school festival, your crossdress appearance caused screams — teacher thought you were a new student.' }, cond: { minAge: 15, maxAge: 18, hasTag: 'cd_awakened', minChr: 6, chance: 0.3 }, effects: { chr: 2, spr: 3 } },
    { text: { zh: '你被选为学校文艺汇演的"女主角"。', en: 'You were chosen as the "leading lady" for the school play.' }, cond: { minAge: 15, maxAge: 18, hasTag: 'cd_awakened', minChr: 7, chance: 0.25 }, effects: { chr: 2, spr: 1, tag: 'cd_actress' } },
    { text: { zh: '你在话剧中的表演太成功了，全校都在讨论"那个女生是谁"。', en: 'Your performance was so good, the whole school asked "who\'s that girl?"' }, cond: { minAge: 15, maxAge: 18, hasTag: 'cd_actress', chance: 0.5 }, effects: { chr: 2, spr: 2 } },
    { text: { zh: '同桌发现了你的秘密，但他说"其实你比女孩子还好看"。', en: 'Your deskmate discovered your secret: "Actually, you\'re prettier than girls."' }, cond: { minAge: 15, maxAge: 18, hasTag: 'cd_awakened', chance: 0.25 }, effects: { spr: 2, chr: 1 } },
    { text: { zh: '你和女生们一起逛街，她们根本没发现异样。', en: 'You went shopping with the girls — they didn\'t notice anything unusual.' }, cond: { minAge: 16, maxAge: 20, hasTag: 'cd_awakened', minChr: 7, chance: 0.25 }, effects: { spr: 2 } },
    { text: { zh: '你参加了学校的选美比赛……并获得了第一名。', en: 'You entered the school beauty contest... and won first place.' }, cond: { minAge: 16, maxAge: 18, hasTag: 'cd_awakened', minChr: 8, chance: 0.15 }, effects: { chr: 3, spr: 2, tag: 'cd_beauty_champ' } },
    { text: { zh: '选美冠军的消息传开后，真相大白——你上了学校论坛热搜。', en: 'When the truth came out about the beauty contest — you trended on the school forum.' }, cond: { minAge: 16, maxAge: 19, hasTag: 'cd_beauty_champ', chance: 0.5 }, effects: { chr: 1, spr: -1 } },
    { text: { zh: '你被体育老师认了出来："你不是那个……"气氛瞬间尴尬。', en: 'The PE teacher recognized you: "Aren\'t you that..." Awkward silence.' }, cond: { minAge: 15, maxAge: 18, hasTag: 'cd_awakened', chance: 0.15 }, effects: { spr: -2 } },
    { text: { zh: '一个女生说想跟你学化妆，你比她画得还好。', en: 'A girl asked you to teach her makeup — you\'re better at it.' }, cond: { minAge: 16, maxAge: 20, hasTag: 'cd_awakened', minChr: 7, chance: 0.2 }, effects: { chr: 1, spr: 2 } },

    // --- 网络发展 ---
    { text: { zh: '🌸 你的女装照在网上火了，粉丝暴涨！', en: '🌸 Your crossdress photos went viral online!' }, cond: { minAge: 16, maxAge: 25, hasTag: 'cd_awakened', minChr: 7, chance: 0.3 }, effects: { chr: 3, mny: 2, spr: 2, tag: 'cd_viral' } },
    { text: { zh: '你开始做女装直播，每次在线人数过万。', en: 'You started crossdressing livestreams — over 10K viewers each time.' }, cond: { minAge: 17, maxAge: 28, hasTag: 'cd_viral', chance: 0.3 }, effects: { mny: 2, chr: 1, spr: 1, tag: 'cd_streamer' } },
    { text: { zh: '你的B站/YouTube频道粉丝突破了50万。', en: 'Your channel passed 500K followers.' }, cond: { minAge: 18, maxAge: 30, hasTag: 'cd_streamer', chance: 0.3 }, effects: { mny: 3, chr: 2, spr: 2 } },
    { text: { zh: '💄 你成了知名的女装博主，收到了品牌代言。', en: '💄 You became a famous crossdress influencer with brand deals.' }, cond: { minAge: 18, maxAge: 30, hasTag: 'cd_awakened', minChr: 9, chance: 0.2 }, effects: { mny: 4, chr: 2, spr: 3, tag: 'cd_influencer' } },
    { text: { zh: '你接到了一个化妆品牌的广告合同，酬劳六位数。', en: 'You got a cosmetics ad contract — six-figure fee.' }, cond: { minAge: 18, maxAge: 32, hasTag: 'cd_influencer', chance: 0.25 }, effects: { mny: 4, chr: 1 } },
    { text: { zh: '有杂志邀请你做封面模特，主题是"打破性别界限"。', en: 'A magazine invited you for a cover shoot: "Breaking Gender Norms."' }, cond: { minAge: 19, maxAge: 30, hasTag: 'cd_influencer', minChr: 9, chance: 0.15 }, effects: { chr: 3, mny: 2, spr: 2, tag: 'cd_cover' } },
    { text: { zh: '你的女装视频上了热搜，评论区分为两派吵得不可开交。', en: 'Your video trended — the comments section split into two warring factions.' }, cond: { minAge: 17, maxAge: 30, hasTag: 'cd_viral', chance: 0.2 }, effects: { chr: 1, spr: -1 } },
    { text: { zh: '你被选为某知名女装品牌的代言人。', en: 'You were chosen as spokesperson for a famous fashion brand.' }, cond: { minAge: 20, maxAge: 32, hasTag: 'cd_influencer', minChr: 10, chance: 0.1 }, effects: { mny: 5, chr: 2, spr: 3 } },
    { text: { zh: '有制片方找你试镜偶像剧的女主角。', en: 'A production company asked you to audition for a drama\'s female lead.' }, cond: { minAge: 18, maxAge: 28, hasTag: 'cd_cover', minChr: 9, chance: 0.15 }, effects: { chr: 2, mny: 3, tag: 'cd_actress_pro' } },
    { text: { zh: '你居然真的拿到了那个角色！观众评价："比真女演员还美。"', en: 'You got the role! Audience review: "Prettier than real actresses."' }, cond: { minAge: 19, maxAge: 30, hasTag: 'cd_actress_pro', chance: 0.4 }, effects: { chr: 3, mny: 4, spr: 3 } },

    // --- 日常搞笑 ---
    { text: { zh: '快递小哥叫你"小姐姐"，你淡定地说了声"谢谢"。', en: 'The delivery guy called you "miss" — you calmly said "thanks."' }, cond: { minAge: 18, maxAge: 35, hasTag: 'cd_awakened', minChr: 7, chance: 0.2 }, effects: { spr: 1 } },
    { text: { zh: '你去女装店试衣服，店员全程没有怀疑。', en: 'You tried on clothes at a women\'s store — no suspicion at all.' }, cond: { minAge: 16, maxAge: 35, hasTag: 'cd_awakened', minChr: 7, chance: 0.2 }, effects: { spr: 2, chr: 1 } },
    { text: { zh: '你发现自己的腰比很多女生都细。内心复杂。', en: 'You discovered your waist is slimmer than most girls\'. Mixed feelings.' }, cond: { minAge: 15, maxAge: 25, hasTag: 'cd_awakened', chance: 0.25 }, effects: { chr: 1 } },
    { text: { zh: '你走在街上被星探搭讪："小姐姐想当模特吗？"', en: 'A talent scout approached you: "Miss, interested in modeling?"' }, cond: { minAge: 16, maxAge: 25, hasTag: 'cd_awakened', minChr: 8, chance: 0.1 }, effects: { chr: 1, spr: 2 } },
    { text: { zh: '你和女朋友/男朋友一起逛街，路人以为你们是闺蜜。', en: 'Shopping with your partner — people thought you were besties.' }, cond: { minAge: 18, maxAge: 30, hasTag: 'cd_awakened', hasTag2: 'partner', minChr: 7, chance: 0.15 }, effects: { spr: 1 } },
    { text: { zh: '你参加了Cosplay大赛，扮演了某动漫的女角色，拿了最佳Cos奖。', en: 'You cosplayed an anime heroine at a convention — won Best Cosplay.' }, cond: { minAge: 16, maxAge: 30, hasTag: 'cd_awakened', minChr: 7, chance: 0.15 }, effects: { chr: 2, spr: 3, tag: 'cd_cosplay' } },
    { text: { zh: '你的Cosplay照片在推特/微博上被转发了十万次。', en: 'Your cosplay photos were retweeted 100K times.' }, cond: { minAge: 17, maxAge: 32, hasTag: 'cd_cosplay', minChr: 8, chance: 0.3 }, effects: { chr: 2, mny: 1, spr: 2 } },
    { text: { zh: '你在女厕排队时被阿姨提醒："小伙子，你走错了。"尴尬爆炸。', en: 'While queuing for the ladies\' room, an auntie said: "Young man, wrong one." Mortifying.' }, cond: { minAge: 16, maxAge: 35, hasTag: 'cd_awakened', chance: 0.1 }, effects: { spr: -3, chr: -1 } },
    { text: { zh: '你的相亲对象第一次见面被你惊艳到了："你确定是男的？"', en: 'Your blind date was stunned: "Are you sure you\'re a guy?"' }, cond: { minAge: 22, maxAge: 35, hasTag: 'cd_awakened', minChr: 8, chance: 0.1 }, effects: { spr: 1, chr: 1 } },
    { text: { zh: '你去做了一次美甲，指甲油的颜色比美甲师推荐的还好看。', en: 'You got a manicure — chose a color even better than the stylist\'s suggestion.' }, cond: { minAge: 17, maxAge: 35, hasTag: 'cd_awakened', chance: 0.15 }, effects: { spr: 1, chr: 1 } },

    // --- 心理/成长 ---
    { text: { zh: '你开始思考"外表真的那么重要吗"。', en: 'You started questioning: "Does appearance really matter that much?"' }, cond: { minAge: 18, maxAge: 30, hasTag: 'cd_awakened', chance: 0.15 }, effects: { int: 1 } },
    { text: { zh: '有人在网上骂你"变态"。你回复："我比你美就是原罪？"', en: 'Someone called you a "freak" online. You replied: "Is being prettier than you a crime?"' }, cond: { minAge: 16, maxAge: 30, hasTag: 'cd_awakened', chance: 0.15 }, effects: { spr: -1, chr: 1 } },
    { text: { zh: '你的父母发现了你的秘密。沉默了很久后，妈妈说："做你自己就好。"', en: 'Your parents discovered your secret. After silence, mom said: "Just be yourself."' }, cond: { minAge: 16, maxAge: 22, hasTag: 'cd_awakened', chance: 0.2 }, effects: { spr: 4, tag: 'cd_accepted' } },
    { text: { zh: '你的父亲花了很长时间才接受，但最终他拍了拍你的肩膀。', en: 'Your father took a long time to accept, but finally patted your shoulder.' }, cond: { minAge: 17, maxAge: 25, hasTag: 'cd_accepted', chance: 0.4 }, effects: { spr: 3 } },
    { text: { zh: '你决定不再隐藏自己的爱好，活得更自在了。', en: 'You decided to stop hiding your hobby — life feels freer.' }, cond: { minAge: 18, maxAge: 30, hasTag: 'cd_accepted', chance: 0.5 }, effects: { spr: 3, chr: 1, tag: 'cd_open' } },
    { text: { zh: '你受邀在TEDx上做了一场关于"性别表达自由"的演讲。', en: 'You were invited to give a TEDx talk on "Freedom of Gender Expression."' }, cond: { minAge: 22, maxAge: 40, hasTag: 'cd_open', minInt: 6, chance: 0.08 }, effects: { chr: 3, int: 1, spr: 3 } },
    { text: { zh: '你收到了一封粉丝信："因为你，我也有勇气做自己了。"', en: 'You received a fan letter: "Because of you, I have the courage to be myself."' }, cond: { minAge: 18, maxAge: 40, hasTag: 'cd_viral', chance: 0.15 }, effects: { spr: 4 } },
    { text: { zh: '你成为了LGBTQ+社区的榜样人物。', en: 'You became a role model in the LGBTQ+ community.' }, cond: { minAge: 20, maxAge: 40, hasTag: 'cd_open', minChr: 8, chance: 0.1 }, effects: { chr: 2, spr: 2, tag: 'cd_icon' } },

    // --- 时尚/职业 ---
    { text: { zh: '你开始学习服装设计，设计了一套"无性别"服装系列。', en: 'You started studying fashion design — created a "gender-neutral" collection.' }, cond: { minAge: 18, maxAge: 30, hasTag: 'cd_awakened', minInt: 5, chance: 0.1 }, effects: { int: 1, chr: 2, tag: 'cd_designer' } },
    { text: { zh: '你设计的服装在时装周上展出了！', en: 'Your fashion designs were showcased at Fashion Week!' }, cond: { minAge: 22, maxAge: 35, hasTag: 'cd_designer', chance: 0.3 }, effects: { mny: 4, chr: 3, spr: 3, tag: 'cd_fashion_week' } },
    { text: { zh: '知名设计师邀请你合作，说"你打破了传统审美的边界"。', en: 'A famous designer invited collaboration: "You break traditional aesthetic boundaries."' }, cond: { minAge: 23, maxAge: 38, hasTag: 'cd_fashion_week', chance: 0.3 }, effects: { mny: 3, chr: 2, spr: 2 } },
    { text: { zh: '你创立了自己的女装品牌，名字就叫"打破边界"。', en: 'You founded your own fashion brand called "Break Boundaries."' }, cond: { minAge: 24, maxAge: 40, hasTag: 'cd_designer', minMny: 5, chance: 0.15 }, effects: { mny: 3, chr: 2, tag: 'cd_brand' } },
    { text: { zh: '你的品牌年收入突破了千万，登上了福布斯。', en: 'Your brand earned $10M annually — you made it to Forbes.' }, cond: { minAge: 28, maxAge: 45, hasTag: 'cd_brand', chance: 0.2 }, effects: { mny: 5, chr: 3, spr: 3 } },
    { text: { zh: '你成为了化妆品行业的顾问，被称为"最懂女人的男人"。', en: 'You became a beauty industry consultant — "the man who understands women best."' }, cond: { minAge: 25, maxAge: 40, hasTag: 'cd_influencer', minInt: 6, chance: 0.1 }, effects: { mny: 3, chr: 2 } },
    { text: { zh: '你在综艺节目上女装出镜，观众评论"这颜值犯规了"。', en: 'You appeared in crossdress on a variety show — "This beauty is illegal."' }, cond: { minAge: 20, maxAge: 35, hasTag: 'cd_awakened', minChr: 9, chance: 0.1 }, effects: { chr: 2, mny: 2, spr: 2 } },
    { text: { zh: '你教男明星如何"反串"角色，成了圈内著名的形象顾问。', en: 'You taught male celebrities "reverse roles" — became a famous image consultant.' }, cond: { minAge: 25, maxAge: 45, hasTag: 'cd_influencer', minChr: 8, chance: 0.08 }, effects: { mny: 3, chr: 2 } },

    // --- 感情线 ---
    { text: { zh: '你遇到了一个完全不在乎你外表性别的人，你们开始交往了。', en: 'You met someone who absolutely didn\'t care about gender expression — you started dating.' }, cond: { minAge: 18, maxAge: 35, hasTag: 'cd_awakened', chance: 0.15 }, effects: { spr: 4, tag: 'partner' } },
    { text: { zh: '你的伴侣帮你化妆的时候说："你真的比我好看。"', en: 'While doing your makeup, your partner said: "You really are prettier than me."' }, cond: { minAge: 19, maxAge: 40, hasTag: 'cd_awakened', hasTag2: 'partner', chance: 0.2 }, effects: { spr: 2, chr: 1 } },
    { text: { zh: '你和伴侣一起出门，被夸"好般配的两位小姐姐！"你们相视而笑。', en: 'You and your partner were complimented: "What a lovely pair of ladies!" You exchanged smiles.' }, cond: { minAge: 20, maxAge: 40, hasTag: 'cd_awakened', hasTag2: 'partner', minChr: 8, chance: 0.15 }, effects: { spr: 3 } },

    // --- 挑战/困难 ---
    { text: { zh: '你在面试时被HR问"你平时打扮这么精致吗？"你微笑回应。', en: 'At an interview, HR asked: "Do you always dress so exquisitely?" You smiled.' }, cond: { minAge: 22, maxAge: 35, hasTag: 'cd_awakened', chance: 0.15 }, effects: { spr: -1 } },
    { text: { zh: '你收到了恶意私信和网暴，但粉丝们帮你反击了。', en: 'You received hateful DMs and cyberbullying, but fans stood up for you.' }, cond: { minAge: 17, maxAge: 35, hasTag: 'cd_viral', chance: 0.15 }, effects: { spr: -2, chr: 1 } },
    { text: { zh: '你因为外表差异在工作中被同事孤立了一阵子。', en: 'You were briefly isolated by colleagues because of your appearance.' }, cond: { minAge: 22, maxAge: 35, hasTag: 'cd_awakened', chance: 0.12 }, effects: { spr: -3, chr: -1 } },
    { text: { zh: '但你用实力证明了自己，同事们开始真正尊重你。', en: 'But you proved yourself with ability — colleagues genuinely respect you now.' }, cond: { minAge: 23, maxAge: 38, hasTag: 'cd_awakened', minInt: 6, chance: 0.3 }, effects: { spr: 3, chr: 1 } },
    { text: { zh: '你在公开场合被人质疑性别，但你从容地回应了。', en: 'Your gender was questioned publicly, but you responded with composure.' }, cond: { minAge: 18, maxAge: 40, hasTag: 'cd_awakened', chance: 0.1 }, effects: { spr: -1, int: 1 } },
    { text: { zh: '你参加了"性别多元化"研讨会，分享了自己的故事。', en: 'You attended a "Gender Diversity" seminar and shared your story.' }, cond: { minAge: 22, maxAge: 40, hasTag: 'cd_open', minInt: 5, chance: 0.1 }, effects: { chr: 2, spr: 2 } },

    // --- 晚年 ---
    { text: { zh: '你回顾自己的人生，觉得勇敢做自己是最正确的选择。', en: 'Looking back, being brave enough to be yourself was the best choice.' }, cond: { minAge: 50, maxAge: 80, hasTag: 'cd_awakened', chance: 0.3 }, effects: { spr: 3 } },
    { text: { zh: '你的衣柜里挂满了各种风格的衣服，每一件都有一段故事。', en: 'Your closet is full of different styles — each has its own story.' }, cond: { minAge: 30, maxAge: 70, hasTag: 'cd_awakened', chance: 0.15 }, effects: { spr: 2 } },
    { text: { zh: '越来越多的年轻人因为你的影响开始勇敢表达自己。', en: 'More and more young people express themselves bravely because of your influence.' }, cond: { minAge: 35, maxAge: 60, hasTag: 'cd_icon', chance: 0.3 }, effects: { spr: 4, chr: 2 } },
    { text: { zh: '你写了一本书《美丽无界》，鼓励每个人做真实的自己。', en: 'You wrote a book "Beauty Without Borders" encouraging everyone to be authentic.' }, cond: { minAge: 30, maxAge: 60, hasTag: 'cd_icon', minInt: 6, chance: 0.15 }, effects: { mny: 2, chr: 2, spr: 3, int: 1 } },
    { text: { zh: '你被授予了"年度最具影响力人物"称号。', en: 'You were named "Most Influential Person of the Year."' }, cond: { minAge: 25, maxAge: 50, hasTag: 'cd_icon', minChr: 9, chance: 0.1 }, effects: { chr: 3, spr: 3, mny: 2 } },
    { text: { zh: '你老了，但你的眼神依然闪耀着自信的光芒。', en: 'You\'re older now, but your eyes still gleam with confidence.' }, cond: { minAge: 55, maxAge: 80, hasTag: 'cd_awakened', chance: 0.25 }, effects: { spr: 2, chr: 1 } },

    // ============================================================
    //  3. 短命体质 (short_lived) — 100+ 事件
    // ============================================================
    // --- 童年与诊断 ---
    { text: { zh: '⚠️ 你从小就体弱多病，经常住院。', en: '⚠️ You\'ve been frail and sickly since childhood.' }, cond: { minAge: 3, maxAge: 5, hasTag: 'short_lived', chance: 0.5 }, effects: { str: -1, spr: -1, tag: 'sl_sickly' } },
    { text: { zh: '医生告诉你的父母，你的身体状况"不太乐观"。', en: 'The doctor told your parents your condition "isn\'t optimistic."' }, cond: { minAge: 5, maxAge: 8, hasTag: 'short_lived', chance: 0.4 }, effects: { spr: -2, tag: 'sl_diagnosed' } },
    { text: { zh: '你小时候经常在医院度过假期，别的孩子在玩，你在打针。', en: 'You spent holidays in hospitals while other kids played.' }, cond: { minAge: 5, maxAge: 10, hasTag: 'sl_sickly', chance: 0.4 }, effects: { spr: -2, int: 1 } },
    { text: { zh: '你因为身体原因不能参加体育课，只能在旁边看着。', en: 'Due to health, you could only watch PE class from the sidelines.' }, cond: { minAge: 6, maxAge: 14, hasTag: 'short_lived', chance: 0.35 }, effects: { spr: -1, str: -1 } },
    { text: { zh: '妈妈总是偷偷哭，以为你不知道。', en: 'Mom often cried secretly, thinking you wouldn\'t notice.' }, cond: { minAge: 5, maxAge: 12, hasTag: 'sl_diagnosed', chance: 0.3 }, effects: { spr: -2 } },
    { text: { zh: '虽然体弱，但你读了比同龄人多十倍的书。', en: 'Though frail, you read ten times more books than your peers.' }, cond: { minAge: 6, maxAge: 15, hasTag: 'short_lived', minInt: 5, chance: 0.4 }, effects: { int: 2, spr: 1 } },
    { text: { zh: '你的病房里有个小伙伴，你们成了最好的朋友。', en: 'A fellow patient in the hospital became your best friend.' }, cond: { minAge: 5, maxAge: 12, hasTag: 'sl_sickly', chance: 0.25 }, effects: { spr: 2, tag: 'sl_hospital_friend' } },
    { text: { zh: '你的病友去世了，你哭了一整晚。', en: 'Your hospital friend passed away. You cried all night.' }, cond: { minAge: 7, maxAge: 20, hasTag: 'sl_hospital_friend', chance: 0.3 }, effects: { spr: -4, tag: 'sl_friend_died' } },
    { text: { zh: '从那以后你决定：活着的每一天都要过得精彩。', en: 'From that day on, you decided: every day alive must be extraordinary.' }, cond: { minAge: 8, maxAge: 22, hasTag: 'sl_friend_died', chance: 0.6 }, effects: { spr: 3, tag: 'sl_seize_day' } },
    { text: { zh: '你在病房窗前看日出，觉得活着真好。', en: 'Watching sunrise from the hospital window — being alive feels wonderful.' }, cond: { minAge: 5, maxAge: 35, hasTag: 'short_lived', chance: 0.2 }, effects: { spr: 2 } },

    // --- 奋斗与珍惜 ---
    { text: { zh: '你比任何人都珍惜时间，制定了详细的人生计划。', en: 'You cherish time more than anyone — detailed life plan.' }, cond: { minAge: 12, maxAge: 18, hasTag: 'short_lived', minInt: 5, chance: 0.3 }, effects: { int: 2, spr: 1, tag: 'sl_life_plan' } },
    { text: { zh: '你在病床上完成了高中的全部课程，成绩比健康同学还好。', en: 'You completed all high school courses from your hospital bed — better grades than healthy classmates.' }, cond: { minAge: 15, maxAge: 17, hasTag: 'short_lived', minInt: 7, chance: 0.3 }, effects: { int: 3, spr: 2, chr: 1 } },
    { text: { zh: '你决定不读大学，而是去做自己最想做的事。', en: 'You decided to skip college and do what you truly want.' }, cond: { minAge: 17, maxAge: 18, hasTag: 'short_lived', chance: 0.3 }, effects: { spr: 2, tag: 'sl_own_path' } },
    { text: { zh: '你用有限的时间学会了绘画，每一幅画都饱含生命力。', en: 'With limited time, you learned to paint — each piece bursting with life.' }, cond: { minAge: 10, maxAge: 30, hasTag: 'short_lived', chance: 0.2 }, effects: { chr: 2, spr: 2, tag: 'sl_artist' } },
    { text: { zh: '你的画作在展览中展出，观众说"从未见过如此炽烈的色彩"。', en: 'Your paintings were exhibited — "Never seen such burning colors."' }, cond: { minAge: 15, maxAge: 35, hasTag: 'sl_artist', minChr: 5, chance: 0.3 }, effects: { chr: 2, mny: 2, spr: 3 } },
    { text: { zh: '你开始写日记，记录每一天的点滴，因为你知道每天都是奢侈。', en: 'You started a diary recording every detail — because each day is a luxury.' }, cond: { minAge: 10, maxAge: 35, hasTag: 'short_lived', chance: 0.25 }, effects: { int: 1, spr: 1, tag: 'sl_diary' } },
    { text: { zh: '你学会了弹钢琴，虽然手指有时候会发抖。', en: 'You learned piano, even though your fingers sometimes tremble.' }, cond: { minAge: 8, maxAge: 25, hasTag: 'short_lived', chance: 0.15 }, effects: { chr: 1, spr: 2, tag: 'sl_piano' } },
    { text: { zh: '你在音乐会上弹奏了自己的曲子，全场起立鼓掌。', en: 'You performed your own composition at a concert — standing ovation.' }, cond: { minAge: 15, maxAge: 35, hasTag: 'sl_piano', chance: 0.3 }, effects: { chr: 3, spr: 4, mny: 1 } },
    { text: { zh: '你用积蓄去了一直想去的地方旅行。', en: 'You used your savings to visit a place you\'ve always dreamed of.' }, cond: { minAge: 16, maxAge: 35, hasTag: 'short_lived', minMny: 3, chance: 0.25 }, effects: { spr: 4, mny: -2, tag: 'sl_dream_trip' } },
    { text: { zh: '你在旅途中看到了极光，觉得这一生没有遗憾了。', en: 'You saw the Northern Lights on your trip — no regrets in this life.' }, cond: { minAge: 16, maxAge: 38, hasTag: 'sl_dream_trip', chance: 0.4 }, effects: { spr: 5 } },

    // --- 爱与被爱 ---
    { text: { zh: '你遇到了一个愿意不顾一切陪伴你的人。', en: 'You met someone willing to stay with you no matter what.' }, cond: { minAge: 16, maxAge: 30, hasTag: 'short_lived', minChr: 4, chance: 0.2 }, effects: { spr: 5, tag: 'partner' } },
    { text: { zh: '你的恋人知道你的情况后，抱着你哭了。然后说："我不后悔。"', en: 'After learning about your condition, your lover cried and said: "I don\'t regret it."' }, cond: { minAge: 17, maxAge: 32, hasTag: 'short_lived', hasTag2: 'partner', chance: 0.5 }, effects: { spr: 4 } },
    { text: { zh: '你们在樱花树下许愿："下辈子也要在一起。"', en: 'Under cherry blossoms, you wished: "Together in the next life too."' }, cond: { minAge: 17, maxAge: 35, hasTag: 'short_lived', hasTag2: 'partner', chance: 0.3 }, effects: { spr: 3 } },
    { text: { zh: '你和恋人举办了一个小小的婚礼，只有最亲近的人参加。', en: 'You had a small wedding with only the closest people.' }, cond: { minAge: 20, maxAge: 35, hasTag: 'short_lived', hasTag2: 'partner', chance: 0.25 }, effects: { spr: 5, tag: 'married' } },
    { text: { zh: '你给恋人写了一封信，藏在了一个只有你们知道的地方。', en: 'You wrote a letter to your lover, hidden in a place only you two know.' }, cond: { minAge: 18, maxAge: 38, hasTag: 'short_lived', hasTag2: 'partner', chance: 0.2 }, effects: { spr: 2, tag: 'sl_letter' } },
    { text: { zh: '你给每一个重要的人都准备了礼物，以备"那一天"。', en: 'You prepared gifts for everyone important, just in case "that day" comes.' }, cond: { minAge: 15, maxAge: 38, hasTag: 'short_lived', chance: 0.15 }, effects: { spr: -1, tag: 'sl_prepared' } },

    // --- 挫折与病痛 ---
    { text: { zh: '你在街上突然晕倒了，被送去急诊。', en: 'You collapsed on the street and were rushed to the ER.' }, cond: { minAge: 10, maxAge: 35, hasTag: 'short_lived', chance: 0.15 }, effects: { str: -2, spr: -2 } },
    { text: { zh: '医生说你的身体指标又恶化了。但你只是笑着点了点头。', en: 'The doctor said your condition worsened. You just smiled and nodded.' }, cond: { minAge: 15, maxAge: 38, hasTag: 'short_lived', chance: 0.2 }, effects: { str: -1, spr: -1 } },
    { text: { zh: '你吃的药越来越多，有些药物的副作用让你很难受。', en: 'More and more medication — side effects make you miserable.' }, cond: { minAge: 10, maxAge: 38, hasTag: 'short_lived', chance: 0.2 }, effects: { str: -1, spr: -2, mny: -1 } },
    { text: { zh: '你做了一次大手术，在ICU住了一个星期。', en: 'You had major surgery and spent a week in ICU.' }, cond: { minAge: 12, maxAge: 35, hasTag: 'short_lived', chance: 0.15 }, effects: { str: -3, mny: -3, tag: 'sl_surgery' } },
    { text: { zh: '手术很成功，医生说你可能比预期活得更久。', en: 'Surgery was successful — doctor said you might live longer than expected.' }, cond: { minAge: 12, maxAge: 36, hasTag: 'sl_surgery', chance: 0.5 }, effects: { spr: 5, str: 1, tag: 'sl_extended' } },
    { text: { zh: '你的头发因为治疗开始大把掉落。照镜子时你强忍着眼泪。', en: 'Treatment caused your hair to fall out. You held back tears in the mirror.' }, cond: { minAge: 10, maxAge: 35, hasTag: 'short_lived', chance: 0.15 }, effects: { chr: -2, spr: -2 } },
    { text: { zh: '你在夜里疼得睡不着，但你不想让任何人担心。', en: 'Pain kept you awake at night, but you didn\'t want anyone to worry.' }, cond: { minAge: 10, maxAge: 38, hasTag: 'short_lived', chance: 0.2 }, effects: { str: -1, spr: -2 } },
    { text: { zh: '你的治疗费用让家里经济陷入困境。你感到深深的愧疚。', en: 'Treatment costs put your family in financial trouble. You felt deep guilt.' }, cond: { minAge: 10, maxAge: 38, hasTag: 'short_lived', chance: 0.15 }, effects: { mny: -3, spr: -3 } },
    { text: { zh: '但妈妈说："钱没了可以再赚，你在就好。"', en: 'Mom said: "Money can be earned again. You being here is what matters."' }, cond: { minAge: 10, maxAge: 38, hasTag: 'short_lived', chance: 0.2 }, effects: { spr: 4 } },

    // --- 活在当下 ---
    { text: { zh: '你做了一个"死前想做的100件事"清单，开始一项一项完成。', en: 'You made a "100 Things Before I Die" list and started checking them off.' }, cond: { minAge: 14, maxAge: 30, hasTag: 'short_lived', chance: 0.2 }, effects: { spr: 3, tag: 'sl_bucket_list' } },
    { text: { zh: '你从清单上划掉了"看海"这一项。大海比想象中还要辽阔。', en: 'You crossed off "See the ocean." The sea was vaster than you imagined.' }, cond: { minAge: 14, maxAge: 35, hasTag: 'sl_bucket_list', chance: 0.3 }, effects: { spr: 3 } },
    { text: { zh: '你尝试了跳伞！教练说你是他见过最勇敢的学员。', en: 'You tried skydiving! The instructor said you were the bravest student ever.' }, cond: { minAge: 16, maxAge: 35, hasTag: 'sl_bucket_list', chance: 0.2 }, effects: { spr: 4, str: 1 } },
    { text: { zh: '你学会了做一道完美的蛋炒饭，妈妈说比她做的还好吃。', en: 'You mastered fried rice — mom said it\'s better than hers.' }, cond: { minAge: 12, maxAge: 35, hasTag: 'short_lived', chance: 0.2 }, effects: { spr: 2 } },
    { text: { zh: '你在半夜偷偷溜出医院，去看了一次流星雨。', en: 'You sneaked out of the hospital at midnight to watch a meteor shower.' }, cond: { minAge: 12, maxAge: 35, hasTag: 'short_lived', chance: 0.1 }, effects: { spr: 4 } },
    { text: { zh: '你在社交媒体上分享了自己的故事，鼓励了无数人。', en: 'You shared your story on social media, inspiring countless people.' }, cond: { minAge: 14, maxAge: 35, hasTag: 'short_lived', chance: 0.1 }, effects: { chr: 3, spr: 3, tag: 'sl_inspiring' } },
    { text: { zh: '你的故事被拍成了纪录片《倒计时人生》。', en: 'Your story was made into a documentary: "Countdown Life."' }, cond: { minAge: 18, maxAge: 38, hasTag: 'sl_inspiring', chance: 0.2 }, effects: { chr: 3, mny: 2, spr: 3 } },
    { text: { zh: '你参加了一场马拉松，虽然只跑了一公里就不行了，但你跑过了起跑线。', en: 'You joined a marathon — only ran 1km, but you crossed the starting line.' }, cond: { minAge: 14, maxAge: 35, hasTag: 'short_lived', chance: 0.08 }, effects: { spr: 4, chr: 1 } },
    { text: { zh: '每个认识你的人都说你是他们见过的最乐观的人。', en: 'Everyone who knows you says you\'re the most optimistic person they\'ve met.' }, cond: { minAge: 15, maxAge: 38, hasTag: 'sl_seize_day', minSpr: 5, chance: 0.2 }, effects: { chr: 2, spr: 2 } },

    // --- 奇迹与希望 ---
    { text: { zh: '新的药物进入了临床试验，医生问你愿不愿意参加。你说"愿意"。', en: 'A new drug entered clinical trials. The doctor asked if you\'d join. "Yes."' }, cond: { minAge: 15, maxAge: 35, hasTag: 'short_lived', chance: 0.1 }, effects: { spr: 1, tag: 'sl_trial' } },
    { text: { zh: '新药物似乎有效！你的指标第一次好转了。', en: 'The new drug seems to work! Your indicators improved for the first time.' }, cond: { minAge: 15, maxAge: 36, hasTag: 'sl_trial', chance: 0.5 }, effects: { str: 2, spr: 4, tag: 'sl_improving' } },
    { text: { zh: '医生惊讶地说你的状况好了很多，简直是奇迹。', en: 'The doctor was amazed: "Your condition has improved dramatically. It\'s a miracle."' }, cond: { minAge: 15, maxAge: 37, hasTag: 'sl_improving', chance: 0.4 }, effects: { str: 2, spr: 5 } },
    { text: { zh: '你打破了医生当初的预言，你还活着！而且活得很好。', en: 'You defied the doctor\'s prediction — you\'re alive, and living well!' }, cond: { minAge: 35, maxAge: 40, hasTag: 'short_lived', chance: 0.3 }, effects: { spr: 5, str: 2, chr: 2, tag: 'sl_miracle' } },
    { text: { zh: '你庆祝了你的"第二个生日"——那个医生说你活不过的年纪。', en: 'You celebrated your "second birthday" — the age doctors said you wouldn\'t reach.' }, cond: { minAge: 35, maxAge: 42, hasTag: 'sl_miracle', chance: 0.5 }, effects: { spr: 5 } },
    { text: { zh: '你在医院等待检查结果时，紧握恋人的手。结果出来了——稳定。', en: 'Waiting for test results, gripping your lover\'s hand. Result: stable.' }, cond: { minAge: 20, maxAge: 38, hasTag: 'short_lived', hasTag2: 'partner', chance: 0.2 }, effects: { spr: 3 } },

    // --- 遗产与告别 ---
    { text: { zh: '你把自己的日记整理成了一本书《如果明天不会来》，感动了无数人。', en: 'You compiled your diary into a book "If Tomorrow Never Comes" — touched millions.' }, cond: { minAge: 18, maxAge: 38, hasTag: 'sl_diary', chance: 0.2 }, effects: { mny: 3, chr: 3, spr: 3, int: 1 } },
    { text: { zh: '你设立了一个基金会，帮助和你有同样遭遇的人。', en: 'You established a foundation to help people with similar conditions.' }, cond: { minAge: 20, maxAge: 38, hasTag: 'sl_inspiring', minMny: 4, chance: 0.15 }, effects: { chr: 3, spr: 3, mny: -2 } },
    { text: { zh: '你在最后写给恋人的信中说："谢谢你让我的人生完整。"', en: 'In your final letter to your lover: "Thank you for making my life complete."' }, cond: { minAge: 25, maxAge: 40, hasTag: 'sl_letter', chance: 0.3 }, effects: { spr: 3 } },
    { text: { zh: '你在阳光明媚的午后，坐在花园里微笑着闭上了眼睛。', en: 'On a sunny afternoon, sitting in the garden, you smiled and closed your eyes.' }, cond: { minAge: 30, maxAge: 42, hasTag: 'short_lived', chance: 0.15 }, effects: { spr: 3 } },
    { text: { zh: '你的葬礼上来了很多人，有些人你连名字都不知道。他们都说"谢谢你"。', en: 'Many came to your funeral — people whose names you didn\'t even know. They all said "thank you."' }, cond: { minAge: 28, maxAge: 42, hasTag: 'sl_inspiring', chance: 0.3 }, effects: { chr: 3 } },
    { text: { zh: '你虽然走得早，但你活过的每一天都比大多数人的一生都精彩。', en: 'You left early, but every day you lived was more vivid than most people\'s entire lives.' }, cond: { minAge: 25, maxAge: 42, hasTag: 'sl_seize_day', chance: 0.3 }, effects: { spr: 4, chr: 2 } },

    // --- 更多日常/细节 ---
    { text: { zh: '你养了一只小猫，它总喜欢趴在你的胸口睡觉。', en: 'You got a kitten — it always sleeps on your chest.' }, cond: { minAge: 12, maxAge: 35, hasTag: 'short_lived', chance: 0.15 }, effects: { spr: 3, tag: 'sl_cat' } },
    { text: { zh: '你在网上认识了一群和你同病相怜的朋友，你们互相鼓励。', en: 'Online, you met people with similar conditions — you encourage each other.' }, cond: { minAge: 12, maxAge: 35, hasTag: 'short_lived', chance: 0.15 }, effects: { spr: 2, tag: 'sl_community' } },
    { text: { zh: '你第一次看到了雪，用发抖的手接住了一片雪花。', en: 'You saw snow for the first time, catching a snowflake with trembling hands.' }, cond: { minAge: 5, maxAge: 35, hasTag: 'short_lived', chance: 0.1 }, effects: { spr: 3 } },
    { text: { zh: '你去了一次游乐园，坐了人生第一次过山车，吓得魂飞魄散但超级开心。', en: 'You went to an amusement park — first roller coaster ever. Terrified but thrilled.' }, cond: { minAge: 12, maxAge: 35, hasTag: 'short_lived', chance: 0.1 }, effects: { spr: 4 } },
    { text: { zh: '你在手术前许了一个愿望："让我再多看一次樱花。"', en: 'Before surgery, you made a wish: "Let me see the cherry blossoms one more time."' }, cond: { minAge: 12, maxAge: 38, hasTag: 'sl_surgery', chance: 0.3 }, effects: { spr: 1 } },
    { text: { zh: '你看到了樱花。全力绽放的樱花。和你一样。', en: 'You saw the cherry blossoms. Blooming with all their might. Just like you.' }, cond: { minAge: 12, maxAge: 38, hasTag: 'short_lived', chance: 0.1 }, effects: { spr: 4 } },
    { text: { zh: '你在医院里教其他小患者画画，他们叫你"画画哥哥/姐姐"。', en: 'You taught other young patients to draw — they call you "Art Big Bro/Sis."' }, cond: { minAge: 12, maxAge: 30, hasTag: 'short_lived', chance: 0.12 }, effects: { spr: 3, chr: 1 } },
    { text: { zh: '你的护工阿姨比你妈妈还关心你，每天给你偷偷带零食。', en: 'Your caregiver auntie cares more than mom — sneaks you snacks daily.' }, cond: { minAge: 8, maxAge: 35, hasTag: 'sl_sickly', chance: 0.2 }, effects: { spr: 2 } },
    { text: { zh: '你给未来的自己写了一封信："如果你能读到这封信，恭喜你。"', en: 'You wrote a letter to your future self: "If you can read this, congratulations."' }, cond: { minAge: 14, maxAge: 30, hasTag: 'short_lived', chance: 0.15 }, effects: { spr: 2, int: 1 } },
    { text: { zh: '多年后你打开了那封信，泪流满面。你活到了。', en: 'Years later, you opened that letter, tears streaming. You made it.' }, cond: { minAge: 30, maxAge: 42, hasTag: 'short_lived', chance: 0.2 }, effects: { spr: 5 } },
    { text: { zh: '你在生日蛋糕上许愿："我只想活久一点。"', en: 'On your birthday cake, you wished: "I just want to live a little longer."' }, cond: { minAge: 10, maxAge: 38, hasTag: 'short_lived', chance: 0.15 }, effects: { spr: -1 } },
    { text: { zh: '你悄悄给父母买了保险，万一你不在了，他们也有保障。', en: 'You secretly bought insurance for your parents — in case you\'re gone.' }, cond: { minAge: 18, maxAge: 38, hasTag: 'short_lived', minMny: 3, chance: 0.15 }, effects: { spr: -1, mny: -1 } },
    { text: { zh: '你的主治医生退休了，他说你是他行医生涯中最难忘的患者。', en: 'Your doctor retired and said you were the most unforgettable patient in his career.' }, cond: { minAge: 20, maxAge: 38, hasTag: 'short_lived', chance: 0.1 }, effects: { spr: 3, chr: 1 } },
    { text: { zh: '你带着氧气瓶去看了一场演唱会，全场一起唱的时候你哭了。', en: 'You attended a concert with an oxygen tank — cried when everyone sang together.' }, cond: { minAge: 15, maxAge: 38, hasTag: 'short_lived', chance: 0.08 }, effects: { spr: 4 } },
    { text: { zh: '你用花了一个月拍了一部关于自己生活的短片，上传后播放量破百万。', en: 'You spent a month filming a short about your life — over a million views.' }, cond: { minAge: 16, maxAge: 35, hasTag: 'short_lived', chance: 0.08 }, effects: { chr: 2, spr: 3, mny: 1 } },
    { text: { zh: '你在深夜写了一首诗："我的生命是一颗流星，短暂却明亮。"', en: 'Late at night, you wrote a poem: "My life is a shooting star — brief but bright."' }, cond: { minAge: 14, maxAge: 38, hasTag: 'short_lived', minInt: 5, chance: 0.12 }, effects: { int: 1, spr: 2 } },
    { text: { zh: '你想要养一棵树，虽然你可能看不到它长大。但你种下了。', en: 'You wanted to plant a tree — you might not see it grow. But you planted it.' }, cond: { minAge: 15, maxAge: 38, hasTag: 'short_lived', chance: 0.1 }, effects: { spr: 3, tag: 'sl_tree' } },

    ];

    window.TALENT_EVENTS_1 = TALENT_EVENTS;
})();
